[options]
girs_dir = "gir-files"
library = "GObject"
version = "2.0"
min_cfg_version = "2.32"
target_path = "."
auto_path = "src/gobject/auto"
work_mode = "normal"
single_version_file = true

generate = [
    "GObject.BindingFlags",
    "GObject.ParamFlags",
]

ignore = [
]

manual = [
    "GObject.Object",
    "GObject.Value",
]

[[object]]
name = "GObject.Binding"
status = "generate"
trait = false
concurrency = "send+sync"

[[object]]
name = "GObject.*"
status = "ignore"
