// This file was generated by gir (d9bce8f) from gir-files (11e0e6d)
// DO NOT EDIT

mod key_file;
pub use self::key_file::KeyFile;

mod flags;
pub use self::flags::KeyFileFlags;
pub use self::flags::KEY_FILE_NONE;
pub use self::flags::KEY_FILE_KEEP_COMMENTS;
pub use self::flags::KEY_FILE_KEEP_TRANSLATIONS;

#[doc(hidden)]
pub mod traits {
}
